# install mariadb on mac
# $ brew install mariadb 
# $ mysql.server start|stop
# init root password at first start: 
# sql> ALTER USER 'root'@'localhost' IDENTIFIED BY 'mypassword';
# sql> flush privileges;
user = "root"
password = "mypassword"
host = "www.baidu.com"
port = 3306
network = "tcp"
dbname = "real_world_medium"
timeout = "10s"
